/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.company.view;

import br.com.company.control.ProdutoControl;
import br.com.company.model.domain.Produto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david.pereira
 */
public class TelaCadastroProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroProdutos
     */
    public TelaCadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaCasdasroProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoQtdproduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoDescricaoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoPrecoUnitario = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        botaoCancelarProduto = new javax.swing.JButton();
        botaoLimparProduto = new javax.swing.JButton();
        botaoSalvarProduto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produtos ");
        setAutoscrolls(true);

        TelaCasdasroProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));

        jLabel1.setText("Nome");

        textoNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeProdutoActionPerformed(evt);
            }
        });
        textoNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoNomeProdutoKeyPressed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        textoQtdproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoQtdprodutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        jLabel4.setText("Preço Unitario");

        textoPrecoUnitario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textoPrecoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPrecoUnitarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Eletronicos", "Eletrodomesticos", "Moveis", "Utilidade Pessoal", "Informatica", "Utilidade Doméstica", "Casa e Banho", "Outros" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Nome", "Descrição", "Categoria", "Quantidade", "Preço Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        javax.swing.GroupLayout TelaCasdasroProdutoLayout = new javax.swing.GroupLayout(TelaCasdasroProduto);
        TelaCasdasroProduto.setLayout(TelaCasdasroProdutoLayout);
        TelaCasdasroProdutoLayout.setHorizontalGroup(
            TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(textoPrecoUnitario))
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(textoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textoQtdproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboCategoria, 0, 260, Short.MAX_VALUE))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        TelaCasdasroProdutoLayout.setVerticalGroup(
            TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6))
                    .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(4, 4, 4)
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(TelaCasdasroProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addGroup(TelaCasdasroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoQtdproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoCancelarProduto.setText("Cancelar");
        botaoCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarProdutoActionPerformed(evt);
            }
        });

        botaoLimparProduto.setText("Limpar");
        botaoLimparProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparProdutoActionPerformed(evt);
            }
        });

        botaoSalvarProduto.setText("Salvar");
        botaoSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaCasdasroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoLimparProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCancelarProduto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaCasdasroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarProduto)
                    .addComponent(botaoLimparProduto)
                    .addComponent(botaoSalvarProduto))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarProdutoActionPerformed
        // TODO add your handling code here:
        salvarProduto();
        preencherTabela();
    }//GEN-LAST:event_botaoSalvarProdutoActionPerformed

    private void botaoLimparProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparProdutoActionPerformed

    private void botaoCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCancelarProdutoActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void textoQtdprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoQtdprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoQtdprodutoActionPerformed

    private void textoNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeProdutoActionPerformed

    private void textoPrecoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrecoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrecoUnitarioActionPerformed

    private void textoNomeProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNomeProdutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeProdutoKeyPressed

    public void salvarProduto() {
        Produto produto = new Produto();
        ProdutoControl produtoControl = new ProdutoControl();

        produto.setNomeProduto(textoNomeProduto.getText());
        produto.setQtdProduto(Long.valueOf(textoQtdproduto.getText()));
        produto.setIdCategoria(comboCategoria.getSelectedItem().toString());
        produto.setPreco(Integer.parseInt(textoPrecoUnitario.getText()));
        produto.setDescricaoproduto(textoDescricaoProduto.getText());

        produtoControl.salvarProduto(produto);
    }

    private void preencherTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaProduto.getModel();
        modelo.setNumRows(0);
        List<Produto> produtos = listarProduto();
        try {
            for (Produto pro : produtos) {
                Object[] row = {pro.getIdProduto(),
                    pro.getNomeProduto(),
                    pro.getDescricaoproduto(),
                    pro.getIdCategoria(),
                    pro.getQtdProduto(),
                    pro.getPreco()
                };
                modelo.addRow(row);
            }
        } catch (Exception e) {
            throw e;
        }
    }

    private List<Produto> listarProduto() {
        ProdutoControl produtoControl = new ProdutoControl();
        return produtoControl.listar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaCasdasroProduto;
    private javax.swing.JButton botaoCancelarProduto;
    private javax.swing.JButton botaoLimparProduto;
    private javax.swing.JButton botaoSalvarProduto;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField textoDescricaoProduto;
    private javax.swing.JTextField textoNomeProduto;
    private javax.swing.JFormattedTextField textoPrecoUnitario;
    private javax.swing.JTextField textoQtdproduto;
    // End of variables declaration//GEN-END:variables
}
